version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli
      - echo "Checking Docker version..."
      - docker --version  # Ensure Docker is available in the environment

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
      - echo "Tagging the Docker image..."
      - docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to Docker Hub..."
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
      - echo "Build and push complete."

env:
  variables:
    DOCKERHUB_USERNAME: sidhulavhare
    DOCKERHUB_PASSWORD: Sidhu@123  # Replace with a secure secret in AWS Secrets Manager
    IMAGE_NAME: my-swiggy          # Replace with your image name
    IMAGE_TAG: latest              # Replace with your desired tag
