version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli
      - echo "Checking Docker version..."
      - docker --version  # Ensure Docker is available in the environment
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 427601800855.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo "Setting up environment variables..."
      # Set the ECR repository URI (replace <aws_account_id> and <repository_name>)
      - REPOSITORY_URI=427601800855.dkr.ecr.us-east-1.amazonaws.com/swiggy
      - IMAGE_TAG=latest
      - echo $REPOSITORY_URI

  build:
    commands:
      - echo "Building the Docker image..."
      # Build the Docker image
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      # Push the Docker image to ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build and push complete."
      - echo '[{"name":"<your-ecs-container-name>","imageUri":"'$REPOSITORY_URI:$IMAGE_TAG'"}]' > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
