version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
      nodejs: 16 # Adjust Node.js version based on your app
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli
      - echo "Node.js version:"
      - node --version
      - echo "Installing project dependencies..."
      - npm install # Ensure your `package.json` includes all necessary dependencies

  build:
    commands:
      - echo "Building the application..."
      - npm run build # Replace with your build command (e.g., `npm run build` or `yarn build`)

  post_build:
    commands:
      - echo "Build complete. Deploying to S3..."
      - aws s3 sync ./build s3://swiggy1 --delete # Replace with your bucket name
      - echo "Deployment complete. Files synced to S3 bucket."

artifacts:
  files:
    - '**/*'
